CREATE TABLE TASKS (
                       TASK_ID NUMBER PRIMARY KEY,
                       TITLE VARCHAR2(100) NOT NULL,
                       DESCRIPTION VARCHAR2(4000),
                       COMPLETED NUMBER(1,0) DEFAULT 0,
                       CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       UPDATED_AT TIMESTAMP
);

CREATE SEQUENCE TASK_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER TASK_TRIGGER
BEFORE INSERT ON TASKS
FOR EACH ROW
BEGIN
SELECT TASK_SEQ.NEXTVAL
INTO :NEW.TASK_ID
FROM DUAL;
END;

CREATE OR REPLACE PACKAGE TASK_PKG AS

FUNCTION GET_ALL_TASKS RETURN SYS_REFCURSOR;

FUNCTION GET_TASK_BY_ID(p_id NUMBER)
RETURN SYS_REFCURSOR;

PROCEDURE CREATE_TASK(
    p_title VARCHAR2,
    p_description VARCHAR2,
    p_id OUT NUMBER
);

PROCEDURE UPDATE_TASK(
    p_id NUMBER,
    p_title VARCHAR2,
    p_description VARCHAR2,
    p_completed NUMBER
);

PROCEDURE DELETE_TASK(p_id NUMBER);

END TASK_PKG;

CREATE OR REPLACE PACKAGE BODY TASK_PKG AS

FUNCTION GET_ALL_TASKS RETURN SYS_REFCURSOR IS
    rc SYS_REFCURSOR;
BEGIN
OPEN rc FOR SELECT * FROM TASKS;
RETURN rc;
END;

FUNCTION GET_TASK_BY_ID(p_id NUMBER)
RETURN SYS_REFCURSOR IS
    rc SYS_REFCURSOR;
BEGIN
OPEN rc FOR SELECT * FROM TASKS WHERE TASK_ID = p_id;
RETURN rc;
END;

PROCEDURE CREATE_TASK(
    p_title VARCHAR2,
    p_description VARCHAR2,
    p_id OUT NUMBER
)
IS
BEGIN
INSERT INTO TASKS(TITLE, DESCRIPTION)
VALUES(p_title, p_description)
    RETURNING TASK_ID INTO p_id;
END;

PROCEDURE UPDATE_TASK(
    p_id NUMBER,
    p_title VARCHAR2,
    p_description VARCHAR2,
    p_completed NUMBER
)
IS
BEGIN
UPDATE TASKS
SET TITLE = p_title,
    DESCRIPTION = p_description,
    COMPLETED = p_completed
WHERE TASK_ID = p_id;
END;

PROCEDURE DELETE_TASK(p_id NUMBER)
IS
BEGIN
DELETE FROM TASKS WHERE TASK_ID = p_id;
END;

END TASK_PKG;